x = float(input())
y = float(input())
add = (x + y)
multiply =(x*y)
division =(x/y)
reminder = (x%y)
square = (x**2)
print("The total Sum is ", add)
print ("Multiplication" , multiply )
print("division of x & y is ", division)
print ("Reminder of x & y is", reminder)
print("Square of x is", square)
